---

name: Prebuild
on:
  push:
    tags:
      - '*'

jobs:

  build-windows:
    name: Build and upload artifact
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            cc: clang
            bin: jsmin-win-x64.exe
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          echo "/c/msys64/mingw64/bin" >> $GITHUB_PATH
      - name: Build
        shell: bash
        run: ${{ matrix.cc }} jsmin.c -o ${{ matrix.bin }}
      - name: Upload artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.bin }}
          overwrite: true
          tag: ${{ github.ref }}

  build-linux:
    name: Build and upload artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: ubuntu_latest
            arch: aarch64
            cc: gcc
            bin: jsmin-lin-aarch64
          - distro: ubuntu_latest
            arch: armv7
            cc: gcc
            bin: jsmin-lin-armv7
          - distro: ubuntu_latest
            arch: riscv64
            cc: gcc
            bin: jsmin-lin-riscv64
          - distro: ubuntu_latest
            arch: none
            cc: gcc
            bin: jsmin-lin-x64
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          echo "/c/msys64/mingw64/bin" >> $GITHUB_PATH
      - if: ${{ matrix.arch != 'none' }}
        uses: uraimo/run-on-arch-action@v2
        name: Build arch
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          install: |
            apt-get update -yq
            apt-get install -yq build-essential
          run: |
            ${{ matrix.cc }} jsmin.c -o ${{ matrix.bin }}
      - if: ${{ matrix.arch == 'none' }}
        name: Build native
        shell: bash
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq build-essential
          ${{ matrix.cc }} jsmin.c -o ${{ matrix.bin }}
      - name: Upload artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.bin }}
          overwrite: true
          tag: ${{ github.ref }}
